### ISSUE TITLE
Conda installation

### ISSUE THREAD

**Issue by ammar-n-abbas** [Kaivalya192/live-pose#1]
Hello, 

Can you provide the requirements.txt file for Conda installation please as we want to run it through ROS. ISAAC ROS Foundation Pose requires a lot of GPU memory.

Thank you

**Comment by Kaivalya192** [comment]
you can refer to 
[https://github.com/NVlabs/FoundationPose](Foundationpose) for conda environment.

**Comment by ammar-n-abbas** [comment]
We have developed this repo for using ROS with RealSense with Conda installation. It also requires only 8GB of GPU

https://github.com/ammar-n-abbas/FoundationPoseROS2

**Comment by Kaivalya192** [comment]
great work @ammar-n-abbas 
i also wanted to intigrate it with ros but due to other works i didnt.
Thank You so much for this contribution!!
