### ISSUE TITLE
Any demo video?

### ISSUE THREAD

**Issue by tungyen** [Kaivalya192/live-pose#4]
I am highly interested in this project so I wonder if you can release some demo result for reference? Thank you very much!

**Comment by Kaivalya192** [comment]
yes sure 

https://github.com/user-attachments/assets/97e0cec3-acb2-4135-8770-7061bfe50993

**Comment by tungyen** [comment]
Thanks for the video. After checking the code, I found you use mesh as the input for Foundation Pose. I  wonder if multiview image could be also possible input in your project based on repo of Foundation Pose. Thank you for the great work!

**Comment by Kaivalya192** [comment]
> Thanks for the video. After checking the code, I found you use mesh as the input for Foundation Pose. I  wonder if multiview image could be also possible input in your project based on repo of Foundation Pose. Thank you for the great work!

Hey there,

I found difficulty in generating object to camera transformation Matrix generation  which is necessary for multi view input.

How can I generate that ?
Any method I should follow for the matrix?
